export const TOGGLE_ALL_GROUPS = "TOGGLE_ALL_GROUPS";
export const TOGGLE_ITEM_GROUP = "TOGGLE_ITEM_GROUP";
export const FETCH_SOURCE_PENDING = "FETCH_SOURCE_PENDING";
export const FETCH_SOURCE_SUCCESS = "FETCH_SOURCE_SUCCESS";
export const FETCH_SOURCE_ERROR = "FETCH_SOURCE_ERROR";